/**
 * Zoho IoT SSL Root CA Certificate
 * 
 * Required for TLS/SSL MQTT connection to Zoho IoT Cloud.
 * Update this if Zoho rotates their certificate authority.
 */

#ifndef CERTIFICATE_H
#define CERTIFICATE_H

const char* root_ca = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJAJC1HiIAZAiUMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkNBMQ8wDQYDVQQIDAZPbnRhcmlvMRAwDgYDVQQHDAdUb3JvbnRvMRMwEQYD
VQQKDApaT0hPIENvcnAuMB4XDTE5MDEyNDA1MjY0NVoXDTI5MDEyMTA1MjY0NVow
RTELMAkGA1UEBhMCQ0ExDzANBgNVBAgMBk9udGFyaW8xEDAOBgNVBAcMB1Rvcm9u
dG8xEzARBgNVBAoMClpPSE8gQ29ycC4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQC7+1xOHRQyOnQTHYj+kfqV5y1zFqU1r7iP4lJkZnqz0Z3rW8k3QZv
...
[REPLACE WITH ACTUAL ZOHO IOT ROOT CA CERTIFICATE]
...
-----END CERTIFICATE-----
)EOF";

#endif // CERTIFICATE_H
